name: APPLICATION SETUP
on: 
    push:
        branches: ["dev"]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: login to docker
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}
            
            - name: set up aws
              uses: aws-actions/configure-aws-credentials@v4
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: us-east-2

            - name: set image version tag
              run: echo "TAG_VERSION=$(date +%s)" >> $GITHUB_ENV

            - name: verify tag
              run: echo "YOUr tag is $TAG_VERSION"
                
            - name: build docker image for app
              run: docker build -t youngestkay/apple-care:${TAG_VERSION} .

            - name: push image to docker hub repo
              run: docker push youngestkay/apple-care:${TAG_VERSION}

            - name: Render task definition
              id: task-def
              uses: aws-actions/amazon-ecs-render-task-definition@v1
              with:
                task-definition: .github/json/task-def.json
                container-name: apple-care-nonprod
                image: youngestkay/apple-care:${{ env.TAG_VERSION }}

            - name: Deploy to ECS
              uses: aws-actions/amazon-ecs-deploy-task-definition@v1
              with:
                task-definition: ${{ steps.task-def.outputs.task-definition }}
                service: github-container-tasks-service-4cj2ihs0
                cluster: apple-care-cluster
                wait-for-service-stability: true




